### ISSUE TITLE
Add Msys2 auto-install support

### ISSUE THREAD

**Issue by RickBarretto** [RickBarretto/arturo#1]
Msys2 current don't have any support with auto-install

## Problems are
- Temporary folder isn't working well
- No one command to unpack `.zip` in Msys default ecosystem

## Solutions
- Generate a `.tar.gz` for WindowsMsys2
  - This file must to be the same as Windows, but packed as a `tar.gz`, not a `.zip`
- Download directly on ~/.arturo/bin and remove `arturo.tar.gz` when clean up

**Comment by RickBarretto** [comment]
## What I've done

- [x] [Add Msys2 auto-install support #1](https://github.com/arturo-lang/arturo-lang.io/pull/1): add msys's auto-install support
- [x] [Add WindowsMsys2 artifacts for releases #730](https://github.com/arturo-lang/arturo/pull/730): add msys' release
- [x] [Add Msys support #3](https://github.com/arturo-lang/nightly/pull/3): add msys' nightly release
